name = "Replicate"
uuid = "e32155d0-cde9-4b54-81dd-56ea588185fd"
authors = ["florian oswald <florian.oswald@gmail.com>"]
version = "0.1.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
